"""add column caseorder

Revision ID: f4a396769214
Revises: None
Create Date: 2016-04-27 19:45:09.925572

"""

# revision identifiers, used by Alembic.
revision = 'f4a396769214'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('test')
    op.add_column('testjob', sa.Column('caseorder', sa.PickleType(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testjob', 'caseorder')
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('jobName', sa.VARCHAR(length=64), nullable=True),
    sa.Column('jobType', sa.INTEGER(), nullable=True),
    sa.Column('relateCases', sa.BLOB(), nullable=True),
    sa.Column('relateDevices', sa.BLOB(), nullable=True),
    sa.Column('testapk', sa.VARCHAR(length=512), nullable=True),
    sa.Column('appPackage', sa.VARCHAR(length=64), nullable=True),
    sa.Column('appActivity', sa.VARCHAR(length=64), nullable=True),
    sa.Column('result', sa.INTEGER(), nullable=True),
    sa.Column('reportID', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.INTEGER(), nullable=True),
    sa.Column('createdtime', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), nullable=True),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('password', sa.VARCHAR(length=128), nullable=True),
    sa.Column('createdtime', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
